sound_master:
  ros__parameters:
    flows: [flow_1]
    flow_1: [sound_recognition, emergency_action]
sound_recognition:
  ros__parameters:
    core: sound_recognition
    afferent: audio_input
    audio_input:
      topics:
        [
          "/audio",
          "/audio/channel0",
          "/audio/channel1",
          "/audio/channel2",
          "/audio/channel3",
          "/audio/channel4",
          "/audio/channel5",
          "/doa",
          "/sed",
        ]
      types:
        [
          "audio_common_msgs/msg/AudioData",
          "audio_common_msgs/msg/AudioData",
          "audio_common_msgs/msg/AudioData",
          "audio_common_msgs/msg/AudioData",
          "audio_common_msgs/msg/AudioData",
          "audio_common_msgs/msg/AudioData",
          "audio_common_msgs/msg/AudioData",
          "geometry_msgs/msg/PoseStamped",
          "sound_msgs/msg/SoundEventDetection",
        ]
    efferent: audio_output
    audio_output:
      topics: ["/sound_detection", "sound_markers"]
      types: ["sound_msgs/msg/SoundDetection", "visualization_msgs/msg/Marker"]
    meta: audio_meta
    coupling: audio_coupling

sound_supervision:
  ros__parameters:
    core: sound_supervision_bt

sound_context_evaluation:
  ros__parameters:
    core: sound_context_evaluation
    afferent: sound_input
    sound_input:
      topics: ["/yolo/detections", "/sound_detection"]
      types: ["yolo_msgs/msg/DetectionArray", "sound_msgs/msg/SoundDetection"]
    efferent: sound_context_output
    sound_context_output:
      topics: ["/sound_controlled"]
      types: ["std_msgs/msg/Bool"]

human_assistance:
  ros__parameters:
    core: human_assistance_bt

emergency_action:
  ros__parameters:
    core: emergency_bt
